### ISSUE TITLE
Handle login flow and logged in status

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1211]
- Handle crash calling `window.ethereum.enable()`
- Detect if naka wallet is logged in, if logged in, then `checkLoggedIn` return true
- if naka wallet is logged out, call `window.ethereum.enable()`

**Comment by BernardHan** [comment]
Here is a problem with `window.ethereum.enable()`:
say a user tries to create event when not loggedin. The wallet login page pops up when user hit create event button, then the user close the popup.

Because  `window.ethereum.enable()` does not return anything if closed, and would await there forever (even if closed) until user login.

If the user does not login, and then goes to other page, and then login, the create event form would popup because the await is over. I think this is a huge UX problem.

**Comment by dwalintukan** [comment]
We need to just remove the `window.ethereum.enable()` logic since it really isn't useful for us in that it doesn't have any sort of callback mechanism.

We need to treat the UI as a state machine, which is how React is supposed to be coded in general. Meaning we know the UI can have different logged in states (in/out) so we need to handle the different cases separately. e.g. what happens if the user tries to exec a tx while logged in, what happens if the user tries to exec a tx while logged out, etc.

If the user is not logged in and they want to create an event (or do any other tx), then when they click the button it should pop up the dialog asking the user to login to Naka Wallet. But, we can't use `window.ethereum.enable()` here because the proper flow would be to have the create event dialog popup on finished login but its not possible with Naka Wallet since we have no callback from the enable call. Therefore, we cannot use the enable() call since it does not provide any help in the proper UX flow.

So my proposed solution is to just show a simple dialog that tells the user to login to Naka Wallet. In addition to making the UX better, while the user is logged out, we should continuously poll and check if the the user has logged in by checking `window.naka.currentProvider.selectedAddress` (or if you found another var that determines if the user is logged in or not). This way we wouldn't have to make the user refresh after they have logged in.
