### ISSUE TITLE
On iOS and Android, after I create an event, it doesn’t redirect to my activities, instead, it stays

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#1406]

**Comment by BernardHan** [comment]
In mobile, the wallet app dialog popup seems stop the react flow.
In `store/TransactionStore.js`, when executing `L194-203`, the dialog pops up, and codes after `L203` never gets executed.

**Comment by BernardHan** [comment]
In fact, same thing happens whenever the app dialog pops up, lines that cause dialog poping up:

1. `store/TransactionStore.js`: `L93-99`
2. `store/TransactionStore.js`: `L125-131`

Issues & bugs in mobile caused by this issue:
1. create event, bet, set result, vote, withdraw transactions are not passed to backend database as pending txs
2. create event, bet, set result, vote, withdraw transactions are not showing pending tx in UI
3. After bet, set result and vote an option, the option area stays expanded
4. After creating event, user does not get redirected to history page.
