### ISSUE TITLE
All time-related actions should be handled in UTC

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#1427]
Seems like a user was able to change their phone time and the bet button was still enabled even though the betEndTime has already passed.

Every time-related action should be converting local time unix -> UTC unix. UTC unix is what the server returns for every timestamp.

**Comment by henryzbw** [comment]
i think our time is already handled as utc, since we use moment.js, it already handled that.

the problem is that we are now between prediction end time and result set start time, so the event status is still 'Betting', and we only check if prediction start time is passed, the right fix should make this event goes to next status when it passed the end time in server

**Comment by dwalintukan** [comment]
You’re correct. This will be handled with removing the result set start time at the contract level.
