### ISSUE TITLE
Do not show events in users withdraws page unless they have >0 balance to withdraw

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#294]
1. Let's only show events that users can withdraw QTUM/BOT. If a users gain 0 or loses their bet, don't show it on withdraw page.
![image](https://user-images.githubusercontent.com/711206/37430220-b9556d20-278e-11e8-8049-d53c0591b6cd.png)

**Comment by dwalintukan** [comment]
Same thing as the other issue. How will the user see info about the event even though they lost? I don't think we should determine for the user what content they should see.what if they want to see how the betting/voting went?

How about we add a filter for `Hide non-winning events`?

**Comment by lillland** [comment]
@dwalintukan user can see all events he participated in Activity history, Once the event finalized,  i think he can check his lost there.

**Comment by lillland** [comment]
![withdraw 2x](https://user-images.githubusercontent.com/5739162/37493524-710f984a-2862-11e8-80b5-689c79ea50d6.png)

**Comment by dwalintukan** [comment]
@lillland @TT1943 ok will change the logic to only show ones that you can act on.

**Comment by dwalintukan** [comment]
@TT1943 @lillland If the user never acts on this event, then they won't be able to see the event during certain stages.

For example:
- I see an event I am interested in the `QTUM Prediction` tab, but I won't participate in it. Maybe I am just interested in the information discovery for this topic.
- Once it goes into the `Result Setting phase`, it disappears on me and I have no way to reach this event because I didn't participate in it.
- After the result gets set, it appears back in my `BOT Court`. IMO, this is a weird UX feel. Having something appearing then disappearing then appearing again.

I'm afraid users might mistake this for a bug with our system.

**Comment by dwalintukan** [comment]
#327

**Comment by TT1943** [comment]
@dwalintukan As discussed, remove 0 winning topics from withdraws

**Comment by dwalintukan** [comment]
#363
