### ISSUE TITLE
TX success, but 100 BOT is not charged

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#385]
When I create an event, I choose a wallet address with QTUM but 0 BOT.
The tx is successful, but the 100 BOT is not charged due to insufficient BOT.
![image](https://user-images.githubusercontent.com/711206/37861669-e044902c-2efb-11e8-938e-d02ea83381fb.png)

**Comment by dwalintukan** [comment]
@tt1943 is your event showing on the dashboard?

**Comment by TT1943** [comment]
No, it is not shown on dashboard. I think we can just merely check the BOT balance to prevent that to happen.

**Comment by dwalintukan** [comment]
@TT1943 This behavior is expected. From the smart contract level, an approve is allowed even if you dont have the BOT. Your `approve` succeeded but your `createEvent` failed since you didnt have the BOT.

Am going to add the check if the user has enough for escrow before allowing them to create the event.
