### ISSUE TITLE
Raised amount doesn't right

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#432]
![image](https://user-images.githubusercontent.com/10339131/38063873-7a3b89ee-32b0-11e8-8635-490a62fb549e.png)
![image](https://user-images.githubusercontent.com/10339131/38063884-8a235fee-32b0-11e8-8b12-cf7739731bb3.png)
it has gone through 4 rounds voting, but shows 0 BOT raised

**Comment by dwalintukan** [comment]
The amount that is showing is actually that Oracle's current round. When a `Voting` status Oracle runs out of arbitration time, that same Oracle shows up on the `Finalize` tab. So whatever was bet during the last Voting round would show up there. It's not a total of all the rounds. We actually don't that info in the Oracle.

I will change it so it doesn't show the BOT amount for Finalize cards. This makes more sense since the amount that was voted on that Oracle is inconsequential since it didn't hit the threshold.
