### ISSUE TITLE
Didn't see 'pending confirmation' on finalizing a topic

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#443]
![image](https://user-images.githubusercontent.com/711206/38119679-6a0c8bea-3378-11e8-8dae-c09c3ab03ed5.png)

Go back to `finalize` tab, there is no `pending confirmation`
![image](https://user-images.githubusercontent.com/711206/38119694-7fbd5fd2-3378-11e8-866f-6edc11707c70.png)

**Comment by liviavinci** [comment]
this is the same as https://github.com/bodhiproject/bodhi-ui/issues/297 right ?

**Comment by dwalintukan** [comment]
@TT1943 oh pending we only have for CreateEvent so far. will add it for Finalize pendings.

**Comment by TT1943** [comment]
@dwalintukan we need to show pending confirmation for all `on-chain` transaction. I think this issue is pretty important.

**Comment by dwalintukan** [comment]
@xiahong @frankhu 
We need to add some more logic to BE to be able to return status for each Oracle. Think we will need to add a `status` field for each Oracle object that searches any pending txs.

@xiahong please note that the `pending` tx status would only be for your user since the DB is local to you.

**Comment by frankobe** [comment]
duplicate #297.
