### ISSUE TITLE
click on tx id redirect to wrong address

### ISSUE THREAD

**Issue by frankobe** [bodhiproject/bodhi-ui#484]
click on txid a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e

Jump tp http://127.0.0.1:5555/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e

{"code":"ResourceNotFound","message":"/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e; caused by Error: ENOENT, ui/activities/undefined/tx/a793f81732c75f40e9fc8e7d7240a2bd1e3c913b2113c876a4d998df2013985e not found in /Volumes/Bodhi 0.7.0-c0-d0/Bodhi.app/Contents/Resources/app.asar"}

**Comment by dwalintukan** [comment]
The issue is this in `routes.js`:
```
const QTUM_EXPLORER = {
  dev: 'https://testnet.qtum.org',
  prod: 'https://explorer.qtum.org',
}[process.env.REACT_APP_ENV];
```

Electron does not have the `process.env.REACT_APP_ENV` var when starting the app. We cannot simply just add it to the webpack config since we can switch between dev and prod on Electron side. 

As Frank suggested, we can pass in something like `qtumHost/tx/{txid}` then we replace `qtumHost` with the correct base path on Graph side.

Also another thing to look at is why the passed in url is being appended to the path that the user is at now:
current path in app: `127.0.0.1/oracles/txid/topicId/oracleId/`
+ txid explorer path: `qtumHost/tx/txid`
These are being concatenated together for some reason. We just need the txid explorer path and not the current path in app.

**Comment by dwalintukan** [comment]
#485 fixed
