### ISSUE TITLE
Launch QTUM qt wallet through Bodhi app

### ISSUE THREAD

**Issue by TT1943** [bodhiproject/bodhi-ui#495]
1. We need to add a button in Bodhi app (Lili will provide the design)
2. The button text will be "Qtum Core Wallet" with Qtum logo
3. On click the the button, we will see a dialog saying "You are about to launch Qtum Core Wallet. Due to the sharing usage of Qtum blockchain data, the Bodhi app will be closed. To launch Bodhi again, you will need to close Qtum Core Wallet, and launch Bodhi app. Are you sure you want to continue to launch Qtum Core Wallet?"

**Comment by dwalintukan** [comment]
@TT1943 This does not seem possible from the UI without some heavy logic. What we can do is add a menu item in the `Electron Menu` > `Launch Qtum Wallet`.

The issue is that the React UI code is not tied to the backend. Meaning it cannot send messages from the UI to backend to tell it to shutdown.

If we put this in the Electron menu, it can be done easily since the Electron code is in the BE code.

**Comment by TT1943** [comment]
Yup, we can put this on the menu first

**Comment by dwalintukan** [comment]
👍

**Comment by dwalintukan** [comment]
https://github.com/bodhiproject/bodhi-graphql/pull/212/files
