### ISSUE TITLE
app will throw error when new block come

### ISSUE THREAD

**Issue by henryzbw** [bodhiproject/bodhi-ui#750]
![image](https://user-images.githubusercontent.com/10339131/42344711-04ea6800-8052-11e8-8f07-ade960f09cd0.png)

**Comment by amazingandyyy** [comment]
![screen shot 2018-07-05 at 16 48 14](https://user-images.githubusercontent.com/7886068/42353104-3f1450ba-8073-11e8-8df5-7490f4ca2979.png)

noted: I fixed it when I developed on the other branch by ignoring the null lol which is not cool.

I don't understand why it gives back `null`.

**Comment by dwalintukan** [comment]
i'll fix this one

**Comment by dwalintukan** [comment]
fixed in https://github.com/bodhiproject/bodhi-server/pull/61
#755 handles errors better in UI

**Comment by dwalintukan** [comment]
@amazingandyyy The reason was because the graphql subscription onSyncInfo emit call from the server was missing the peerNodeCount param so addressBalances was being passed in undefined.

Fixed this in my server PR. Also see my UI PR to have better error handling for the subscription. Just checking for null is not sufficient enough. The payload for an error, eg. The addressBalance being undefined comes back in the `next` block of the subscription and that needed to be handled too.
