### ISSUE TITLE
Crash when clicking into unconfirmed Oracle

### ISSUE THREAD

**Issue by dwalintukan** [bodhiproject/bodhi-ui#840]
1. create event
2. click into pending oracle from `Qtum Prediction`
3. crash

![image](https://user-images.githubusercontent.com/4350404/44097270-907188de-a007-11e8-8ef9-d4fd9779d112.png)

**Comment by ippudo** [comment]
This bug is related to the transfer between CREATE_EVENT tx and APPROVE_CREATE_EVENT tx.

Once a CREATE_EVENT transaction for an unconfirmed oracle has been created, the oracle page with the APPROVE_CREATE_EVENT transaction address of this oracle will longer available and make the oracle page crash.

**Comment by dwalintukan** [comment]
#848
